name: Plox CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up project
      run: make setup

    - name: Build extension
      run: make build

    - name: Install Playwright Browsers
      run: |
        source env.sh
        npx playwright install --with-deps chromium

    - name: Run tests
      run: make test
